画像URLから画像データを取得し、ポケモンの画像を表示させる
y-sugiyama654/PokeChallenge01 pull request #8
Opened 2022-12-12 14:31 UTC by y-sugiyama654

2022-12-15 14:03 UTC, techsta-inc requested changes

2022-12-15 14:03 UTC, techsta-inc commented on PokeChallenge01/View/PokeTableViewCell.swift
> +    let imageUrl: String = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"
setImage関数の中でしか利用しないのに、
外から見える状態になっているようです👀
外のクラスから見える状態 > クラスの中のどこからも見える状態 > クラスの中の一部からしか見えない状態
理想は、使用する範囲内に収まることなので
publicやprivate、あるいはメソッドの中に内包してあげたいです👀

2022-12-18 02:11 UTC, sosuiiii approved these changes
approveしちゃいますね！

2022-12-18 05:06 UTC, techsta-inc approved these changes

2022-12-20 14:09 UTC, y-sugiyama654 commented on PokeChallenge01/View/PokeTableViewCell.swift
> +    let imageUrl: String = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"
レビューありがとうございます。
返信遅くなりました、申し訳ありません。
private修飾子追加しました。

2022-12-20 14:09 UTC, y-sugiyama654 commented
こちらマージしちゃいます。

2022-12-20 14:11 UTC, merged